##spring.application.name=m2p6
server:
  port: 8081
  error:
    include-message: always

spring:
  #Configuracion de migracion
  flyway:
    enabled: true
    baselineVersion: 1
    locations:
      classpath: db/migration
    sqlMigrationSuffixes: .sql
    baselineOnMigrate: true
    sqlMigrationPrefix: V
    schemas: public
  #Conexion a base de datos--info de herok
  datasource:
    url: jdbc:postgresql://contptg:5432/bdatos?socketTimeout=3
    username: postgres
    password: 1234
    driverClassName: org.postgresql.Driver